version: 2

jobs:
  tests:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          make test || exit 1

workflows:
  version: 2
  test_and_release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
