version: 2

jobs:
  tests:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          make test -C tests || exit 1
  release:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          make release TAG=$CIRCLE_TAG || exit 1

workflows:
  version: 2
  test_and_release:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - tests
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
