version: 2

jobs:
  tests:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: |
          make test -C tests || exit 1
  release:
    machine:
      enabled: true
    tags: /[0-9]+(\.[0-9]+)*/
    steps:
      - run: |
          make release TAG=$CIRCLE_TAG || exit 1

workflows:
  version: 2
  test_and_release:
    jobs:
      - tests
      - release
