version: 2

dependencies:
  pre:
    - sudo apt-get install -y make

jobs:
  build:
    machine:
      enabled: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: |
          make test -C tests || exit 1
  release:
    machine:
      enabled: true
    tag: /[0-9]+(\.[0-9]+)*/
    steps:
      - run: |
          make release TAG=$CIRCLE_TAG || exit 1

