name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run on architecture ppc64le
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ppc64le
          distro: alpine_latest
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          run: make test
